// Serializers for the two generated data files.
//
// src/data/levels.js is rewritten in place by splicing on sentinels rather than
// regenerating from a template, so the hand-written header comment and the
// derivation code at the bottom survive untouched. String fields go through a
// real escaper — six entries in the corpus contain apostrophes.
import { readFile, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = join(__dirname, '..')
const LEVELS_PATH = join(ROOT, 'src/data/levels.js')
const SENTENCES_PATH = join(ROOT, 'src/data/sentences.js')

// Single-quoted JS string literal, correctly escaped.
const q = (s) => `'${String(s).replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`

// Rewrite the `words` array and LEVEL_NAMES, preserving everything else verbatim.
export async function writeLevelsFile(words, themes) {
  const src = await readFile(LEVELS_PATH, 'utf8')
  const lines = src.split('\n')

  const startIdx = lines.findIndex((l) => l.startsWith('export const words = ['))
  if (startIdx === -1) throw new Error('levels.js: could not find `export const words = [`')
  let endIdx = -1
  for (let i = startIdx + 1; i < lines.length; i++) {
    if (lines[i] === ']') { endIdx = i; break }
  }
  if (endIdx === -1) throw new Error('levels.js: could not find the `]` closing the words array')

  const sorted = [...words].sort((a, b) => a.level - b.level || a.order - b.order)
  const wordLines = sorted.map(
    (w) =>
      `  { id: ${q(w.id)}, hanzi: ${q(w.hanzi)}, pinyin: ${q(w.pinyin)}, ` +
      `english: ${q(w.english)}, level: ${w.level}, order: ${w.order} },`
  )

  // LEVEL_NAMES may be the original one-liner (`= {} // comment`) or a block we
  // wrote on a previous run; handle both.
  const nameIdx = lines.findIndex((l) => l.startsWith('const LEVEL_NAMES'))
  if (nameIdx === -1) throw new Error('levels.js: could not find `const LEVEL_NAMES`')
  let nameEnd = nameIdx
  if (!lines[nameIdx].includes('{}')) {
    for (let i = nameIdx + 1; i < lines.length; i++) {
      if (lines[i].startsWith('}')) { nameEnd = i; break }
    }
  }

  const themeLines = [
    'const LEVEL_NAMES = {',
    ...Object.keys(themes)
      .map(Number)
      .sort((a, b) => a - b)
      .map((lvl) => `  ${lvl}: { name: ${q(themes[lvl].name)}, subtitle: ${q(themes[lvl].subtitle)} },`),
    '}',
  ]

  const out = [
    ...lines.slice(0, startIdx + 1),
    ...wordLines,
    ...lines.slice(endIdx, nameIdx),
    ...themeLines,
    ...lines.slice(nameEnd + 1),
  ]
  await writeFile(LEVELS_PATH, out.join('\n'))
  return sorted.length
}

const HEADER = `// Pre-generated practice sentences, each constrained to its level's cumulative
// word pool (levels 1..N). Generated by scripts/generate-sentences.mjs from
// scripts/curriculum.json, and checked by scripts/validate-data.mjs.
//
// \`tokens\` is authoritative: each element is exactly one pool word's \`hanzi\` and
// becomes one tappable tile in the sentence builder. \`tokenIds\` is the parallel
// array of word ids, resolved at generation time so the runtime never has to
// segment Chinese or disambiguate a repeated hanzi. \`hanzi\` is the tokens joined
// together plus punctuation, for display and text-to-speech.
//
// \`id\` is a stable UUID, for the same reason word ids are: it keys the sentence's
// own progress record in localStorage.
export const sentences = [`

export async function writeSentencesFile(sentences) {
  const sorted = [...sentences].sort((a, b) => a.level - b.level)
  const body = sorted.map((s) => {
    const tokens = s.tokens.map(q).join(', ')
    const ids = s.tokenIds.map(q).join(', ')
    return [
      '  {',
      `    id: ${q(s.id)},`,
      `    level: ${s.level},`,
      `    tokens: [${tokens}],`,
      `    tokenIds: [${ids}],`,
      `    hanzi: ${q(s.hanzi)},`,
      `    pinyin: ${q(s.pinyin)},`,
      `    english: ${q(s.english)},`,
      '  },',
    ].join('\n')
  })

  const out = [
    HEADER,
    ...body,
    ']',
    '',
    'export const sentencesForLevel = (level) => sentences.filter((s) => s.level === level)',
    '',
    '// Cumulative pool, mirroring cardsUpToLevel: everything up to and including `level`.',
    'export const sentencesUpToLevel = (level) => sentences.filter((s) => s.level <= level)',
    '',
  ].join('\n')
  await writeFile(SENTENCES_PATH, out)
  return sorted.length
}
